import React, { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, MousePointer2, ShoppingBag, Users } from 'lucide-react';

const shortDate = value => new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
export default function AdminInsights({ data }) {
  const [metric, setMetric] = useState('visitors');
  const chart = data.daily;
  const groupSize = data.range.days > 90 ? 30 : data.range.days > 30 ? 7 : 1;
  const plotted = groupSize === 1 ? chart : Array.from({length:Math.ceil(chart.length/groupSize)},(_,i) => {
    const group = chart.slice(i*groupSize,(i+1)*groupSize);
    return { date:group[0].date, endDate:group.at(-1).date, visitors:group.reduce((n,d)=>n+d.visitors,0), buyClicks:group.reduce((n,d)=>n+d.buyClicks,0), purchases:group.reduce((n,d)=>n+d.purchases,0), revenue:group.reduce((n,d)=>n+d.revenue,0) };
  });
  const max = Math.max(1, ...plotted.map(d => d[metric]));
  const labels = { visitors:'Visitors', buyClicks:'Buy clicks', purchases:'Purchases', revenue:'Revenue' };
  return <div className="insights-page">
    <div className="insights-intro"><div><span>SALES JOURNEY / {data.range.days} DAYS</span><h2>From first visit to paid access.</h2><p>Counts are based on this website’s own activity. One visitor is identified by a browser cookie; a person using another browser may count again.</p></div><div className="insights-conversion"><strong>{data.conversion}%</strong><span>VISIT TO PURCHASE</span></div></div>
    <div className="insights-metrics"><div><span><Users size={17}/> UNIQUE VISITORS</span><strong>{data.visitors}</strong><small>{data.pageViews} page views</small></div><div><span><MousePointer2 size={17}/> BUY CLICKS</span><strong>{data.buyClicks}</strong><small>unique visitors who tapped a buy button</small></div><div><span><ShoppingBag size={17}/> CHECKOUTS STARTED</span><strong>{data.checkouts}</strong><small>{data.checkoutVisitors} unique visitors</small></div><div><span><ArrowUpRight size={17}/> REAL PURCHASES</span><strong>{data.purchases}</strong><small>₹{data.revenue.toLocaleString('en-IN')} in revenue</small></div></div>
    <div className="insights-middle"><div className="admin-panel"><div className="panel-top"><span>WHERE PEOPLE STOP</span><span>CONVERSION FUNNEL</span></div><h2>Interest and drop-off.</h2><div className="funnel-line"><span>Visited site</span><div><i style={{width:'100%'}}/></div><b>{data.visitors}</b></div><div className="funnel-line"><span>Clicked buy</span><div><i style={{width:`${data.visitors ? Math.max(2,data.buyClicks/data.visitors*100) : 0}%`}}/></div><b>{data.buyClicks}</b></div><div className="funnel-line"><span>Started checkout</span><div><i style={{width:`${data.visitors ? Math.max(2,data.checkoutVisitors/data.visitors*100) : 0}%`}}/></div><b>{data.checkoutVisitors}</b></div><div className="funnel-line"><span>Purchased</span><div><i style={{width:`${data.visitors ? Math.max(2,data.purchases/data.visitors*100) : 0}%`}}/></div><b>{data.purchases}</b></div><div className="funnel-note"><ArrowDownRight size={18}/><div><strong>{data.clickNoPurchase} interested visitors did not purchase</strong><p>They tapped a buy button during this period but have no real paid order in the selected period. Local test orders are excluded.</p></div></div></div>
    <div className="admin-panel"><div className="panel-top"><span>PERFORMANCE TREND</span><span>{groupSize === 1 ? 'DAILY' : groupSize === 7 ? 'WEEKLY' : 'MONTHLY'}</span></div><h2>See the pattern.</h2><div className="insights-switch">{Object.entries(labels).map(([key,label]) => <button key={key} className={metric===key?'active':''} onClick={() => setMetric(key)}>{label}</button>)}</div><div className="insights-chart" role="img" aria-label={`${labels[metric]} by ${groupSize === 1 ? 'day' : groupSize === 7 ? 'week' : 'month'}`}>{plotted.map((d,i) => <div key={d.date} title={`${shortDate(d.date)}${d.endDate ? `–${shortDate(d.endDate)}` : ''}: ${metric==='revenue'?'₹':''}${d[metric]}`}><span style={{height:`${d[metric] ? Math.max(4,d[metric]/max*100) : 0}%`}}/><small>{i===0 || i===plotted.length-1 || (plotted.length<=7) || i%Math.ceil(plotted.length/6)===0 ? shortDate(d.date) : ''}</small></div>)}</div></div></div>
    <section className="admin-panel insights-table"><div className="panel-top"><span>PAGES PEOPLE OPEN</span><span>TOP {data.topPages.length}</span></div><h2>Traffic by page.</h2><div className="top-pages">{data.topPages.map(page => <div key={page.path}><strong>{page.path}</strong><span>{page.views} {page.views === 1 ? 'view' : 'views'}</span></div>)}{!data.topPages.length && <p>Page visits will appear here.</p>}</div></section>
    <section className="admin-panel insights-table"><div className="panel-top"><span>DAILY BREAKDOWN</span><span>{data.range.days} DAYS</span></div><h2>Every day, in detail.</h2><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Date</th><th>Visitors</th><th>Page views</th><th>Buy clicks</th><th>Checkouts</th><th>Purchases</th><th>Revenue</th></tr></thead><tbody>{[...chart].reverse().map(d => <tr key={d.date}><td>{shortDate(d.date)}</td><td>{d.visitors}</td><td>{d.pageViews}</td><td>{d.buyClicks}</td><td>{d.checkouts}</td><td>{d.purchases}</td><td>₹{d.revenue.toLocaleString('en-IN')}</td></tr>)}</tbody></table></div></section>
  </div>;
}
