import React, { useCallback, useEffect, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, ClipboardList, FileText, IndianRupee, Plus, Save, Trash2, UploadCloud, Users } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { api } from '../services/api';
import AdminInsights from '../components/admin/AdminInsights';

const emptyQuestion = { subjectId:'polity', prompt:'', options:['','','',''], correctIndex:0, explanation:'' };
export default function AdminPanel() {
  const { session, loading, navigate, catalog, refresh, showToast } = useStore();
  const [tab, setTab] = useState('overview');
  const [overview, setOverview] = useState(null);
  const [config, setConfig] = useState(null);
  const [question, setQuestion] = useState(emptyQuestion);
  const [editingId, setEditingId] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [period, setPeriod] = useState(30);
  const [update, setUpdate] = useState({ title:'', message:'' });
  const [studentDetail, setStudentDetail] = useState(null);
  const load = useCallback(async () => {
    const data = await api(`/api/admin/overview?days=${period}`);
    setOverview(data); setConfig(data.config);
  }, [period]);
  useEffect(() => { if (session?.role === 'admin') load().catch(err => setError(err.message)); }, [session?.role, load]);
  const run = async (action, success) => {
    setBusy(true); setError('');
    try { await action(); await Promise.all([load(), refresh()]); if (success) showToast(success); return true; }
    catch (err) { setError(err.message); return false; }
    finally { setBusy(false); }
  };
  if (loading) return <main className="route-gate"><p>Opening admin…</p></main>;
  if (session?.role !== 'admin') return <main className="route-gate"><div className="section-kicker">ADMIN ACCESS</div><h1>Sign in to manage CivilPrelims.</h1><button className="btn btn-coral" onClick={() => navigate('login')}>Admin sign in <ArrowRight size={18}/></button></main>;
  const saveConfig = (e) => { e.preventDefault(); run(() => api('/api/admin/config', { method:'PUT', body:JSON.stringify(config) }), 'Offer updated.'); };
  const uploadPdf = async (file) => {
    if (!file) return;
    if (file.type !== 'application/pdf' || file.size > 25*1024*1024) { setError('Choose a PDF smaller than 25 MB.'); return; }
    try { const base64 = await new Promise((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); });
      await run(() => api('/api/admin/pdf', { method:'POST', body:JSON.stringify({ name:file.name, base64 }) }), 'Main PDF updated.');
    } catch (err) { setError(err.message || 'Could not read that PDF.'); }
  };
  const saveQuestion = async (e) => {
    e.preventDefault();
    const saved = await run(() => api(`/api/admin/questions${editingId ? '/'+editingId : ''}`, { method:editingId ? 'PUT' : 'POST', body:JSON.stringify(question) }), editingId ? 'Question updated.' : 'Question added.');
    if (saved) { setQuestion(emptyQuestion); setEditingId(null); }
  };
  const postUpdate = async (e) => { e.preventDefault(); if (await run(() => api('/api/admin/updates', { method:'POST', body:JSON.stringify(update) }), 'Update published.')) setUpdate({title:'',message:''}); };
  const viewStudent = async (email) => { try { setError(''); setStudentDetail(await api(`/api/admin/students/${encodeURIComponent(email)}`)); } catch (err) { setError(err.message); } };
  const edit = (q) => { setQuestion({ subjectId:q.subjectId, prompt:q.prompt, options:[...q.options], correctIndex:q.correctIndex, explanation:q.explanation }); setEditingId(q.id); setTab('questions'); window.scrollTo(0,0); };
  const remove = (q) => { if (window.confirm('Delete this question from the student test?')) run(() => api(`/api/admin/questions/${q.id}`, { method:'DELETE' }), 'Question deleted.'); };
  return <main className="admin-page"><div className="container"><div className="admin-hero"><div><div className="section-kicker">CIVILPRELIMS / CONTROL ROOM</div><h1>Know what is happening.<br/><em>Shape what comes next.</em></h1><p>Manage the offer, publish the paper and build the practice library from one place.</p></div><div className="admin-hero-mark"><BookOpen size={46}/></div></div>
    <div className="admin-tabs">{[['overview','Overview'],['analytics','Traffic & sales'],['students','Students'],['product','Price & PDF'],['questions','Test questions'],['updates','Updates'],['orders','Purchases']].map(([key,label]) => <button key={key} className={tab===key?'active':''} onClick={() => setTab(key)}>{label}</button>)}</div>
    <div className="admin-period"><span>REPORTING PERIOD</span><select aria-label="Reporting period" value={period} onChange={e => setPeriod(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last 365 days</option></select><small>Revenue and traffic use the selected period. Test orders never count as revenue.</small></div>
    {error && <p className="admin-error" role="alert">{error}</p>}
    {!overview ? <p className="admin-loading">Loading admin data…</p> : <>
      {tab === 'overview' && <><div className="admin-stats"><div><span><Users size={21}/> REAL PURCHASES</span><strong>{overview.purchases}</strong><small>Verified paid orders in period</small></div><div><span><IndianRupee size={21}/> REAL REVENUE</span><strong>₹{overview.revenue.toLocaleString('en-IN')}</strong><small>Captured payments in period</small></div><div><span><BarChart3 size={21}/> UNIQUE VISITORS</span><strong>{overview.visitors}</strong><small>Visitors in period</small></div><div><span><ClipboardList size={21}/> BUY CLICKS, NO SALE</span><strong>{overview.clickNoPurchase}</strong><small>Interested visitors without a purchase</small></div></div><div className="admin-overview-grid"><div className="admin-panel"><div className="panel-top"><span>CURRENT OFFER</span><span>01</span></div><h2>₹{overview.config.price}</h2><p>{overview.config.title}</p><button className="panel-link" onClick={() => setTab('product')}>Edit price & paper <ArrowRight size={17}/></button></div><div className="admin-panel"><div className="panel-top"><span>MAIN PDF</span><span>02</span></div><h2>{overview.pdf ? 'Uploaded' : 'Missing'}</h2><p>{overview.pdf?.name || 'Upload the main paper before live checkout.'}</p><button className="panel-link" onClick={() => setTab('product')}>Manage PDF <ArrowRight size={17}/></button></div></div><button className="admin-insights-link" onClick={() => setTab('analytics')}>See daily traffic, checkout activity and revenue <ArrowRight size={18}/></button></>}
      {tab === 'overview' && <div className="admin-lifetime"><span>ALL-TIME TOTALS</span><div><strong>{overview.lifetimeStudents}</strong><small>real students</small></div><div><strong>{overview.lifetimePurchases}</strong><small>paid orders</small></div><div><strong>₹{overview.lifetimeRevenue.toLocaleString('en-IN')}</strong><small>revenue</small></div><div><strong>{overview.totalTestAttempts}</strong><small>test attempts</small></div><div><strong>{overview.testPurchases}</strong><small>local test orders in period</small></div></div>}
      {tab === 'analytics' && <AdminInsights data={overview} />}
      {tab === 'students' && <section className="admin-panel"><div className="panel-top"><span>STUDENT ACTIVITY & ACCESS</span><span>{overview.customers.length} ACCOUNTS</span></div><h2>People behind the numbers.</h2><p>Purchasers, their practice, access codes and account roles. Test accounts are marked clearly.</p><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Student</th><th>Access code</th><th>Role</th><th>Joined</th><th>Tests</th><th>Average score</th><th>Details</th></tr></thead><tbody>{overview.customers.map(c => <tr key={c.email}><td><strong>{c.email}</strong><br/><small>+91 {c.phone} {c.testMode && ' · TEST'}</small></td><td><code>{c.accessCode || '—'}</code></td><td><select value={c.role || 'student'} onChange={e => run(() => api(`/api/admin/students/${encodeURIComponent(c.email)}`, {method:'PUT', body:JSON.stringify({role:e.target.value})}), 'Role updated.')}><option value="student">Student</option><option value="admin">Admin</option></select></td><td>{new Date(c.joinedAt).toLocaleDateString('en-IN')}</td><td>{c.tests}</td><td>{c.averageScore == null ? '—' : `${c.averageScore}%`}</td><td><button className="table-action" onClick={() => viewStudent(c.email)}>Activity <ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!overview.customers.length && <div className="orders-empty">No student accounts yet.</div>}</div>{studentDetail && <div className="student-detail"><div className="panel-top"><span>{studentDetail.email}</span><button onClick={() => setStudentDetail(null)}>CLOSE</button></div><p><strong>Role:</strong> {studentDetail.role} · <strong>Access code:</strong> <code>{studentDetail.accessCode || '—'}</code></p><h3>Test attempts</h3><div className="student-detail-list">{studentDetail.attempts.map(a => <div key={a.id}><strong>{a.subjectName}</strong><span>{a.correct}/{a.total} correct · {new Date(a.at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span></div>)}{!studentDetail.attempts.length && <p>No tests completed yet.</p>}</div><h3>Recent activity</h3><div className="student-detail-list">{studentDetail.events.map(e => <div key={e.id}><strong>{({test_completed:'Completed a test',pdf_view:'Opened PDF',pdf_download:'Downloaded PDF',checkout_started:'Started checkout',purchase:'Purchased access'})[e.type] || e.type}</strong><span>{e.detail && `${e.detail} · `}{new Date(e.at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span></div>)}</div></div>}</section>}
      {tab === 'updates' && <div className="admin-product-grid"><section className="admin-panel"><div className="panel-top"><span>STUDENT ANNOUNCEMENTS</span><span>01</span></div><h2>Post an update.</h2><p>Share new paper versions, added questions or study notes. Students see updates in their profile.</p><form className="admin-form" onSubmit={postUpdate}><label htmlFor="update-title">Title</label><input id="update-title" required minLength={3} value={update.title} onChange={e => setUpdate({...update,title:e.target.value})}/><label htmlFor="update-message">Message</label><textarea id="update-message" required minLength={10} value={update.message} onChange={e => setUpdate({...update,message:e.target.value})}/><button className="btn btn-dark" disabled={busy} type="submit"><Plus size={17}/> Publish update</button></form></section><section className="admin-panel"><div className="panel-top"><span>PUBLISHED</span><span>{overview.updates.length} UPDATES</span></div><h2>Latest updates.</h2><div className="admin-question-list">{overview.updates.map(u => <article key={u.id}><span>{new Date(u.at).toLocaleDateString('en-IN')}</span><h3>{u.title}</h3><p>{u.message}</p><div><button onClick={() => { if (window.confirm('Remove this update?')) run(() => api(`/api/admin/updates/${u.id}`,{method:'DELETE'}),'Update removed.'); }}><Trash2 size={16}/> Remove</button></div></article>)}{!overview.updates.length && <p className="orders-empty">No updates posted yet.</p>}</div></section></div>}
      {tab === 'product' && <div className="admin-product-grid"><section className="admin-panel"><div className="panel-top"><span>OFFER DETAILS</span><span>01</span></div><h2>Price & product</h2><p>These details appear on the landing page and in checkout.</p><form onSubmit={saveConfig} className="admin-form"><label htmlFor="product-price">Price in rupees</label><input id="product-price" type="number" min="1" max="50000" required value={config?.price ?? ''} onChange={e => setConfig({ ...config, price:Number(e.target.value) })}/><label htmlFor="product-title">Product title</label><input id="product-title" required value={config?.title ?? ''} onChange={e => setConfig({ ...config, title:e.target.value })}/><label htmlFor="product-subtitle">Short description</label><textarea id="product-subtitle" value={config?.subtitle ?? ''} onChange={e => setConfig({ ...config, subtitle:e.target.value })}/><label htmlFor="paper-label">PDF title in student library</label><input id="paper-label" value={config?.paperLabel ?? ''} onChange={e => setConfig({ ...config, paperLabel:e.target.value })}/><button className="btn btn-dark" type="submit" disabled={busy}><Save size={17}/> Save offer</button></form></section><section className="admin-panel"><div className="panel-top"><span>DOCUMENT DELIVERY</span><span>02</span></div><h2>Main PDF</h2><p>Upload the paper students will read and download after purchase. A new upload replaces the current file.</p><div className="pdf-status"><FileText size={25}/><div><strong>{overview.pdf?.name || 'No PDF uploaded'}</strong><small>{overview.pdf ? `${(overview.pdf.size/1024/1024).toFixed(1)} MB · Updated ${new Date(overview.pdf.updatedAt).toLocaleDateString()}` : 'PDF, maximum 25 MB'}</small></div></div><label className="upload-control" htmlFor="main-pdf"><UploadCloud size={23}/><strong>{busy ? 'Uploading…' : 'Choose a PDF file'}</strong><span>Tap here to upload or replace</span></label><input id="main-pdf" className="visually-hidden" type="file" accept="application/pdf,.pdf" onChange={e => uploadPdf(e.target.files?.[0])}/>{overview.pdf && <a className="panel-link" href="/api/pdf" target="_blank" rel="noreferrer">View current PDF <ArrowRight size={17}/></a>}{overview.pdf?.demo && <div className="demo-document-note">This is the local 3-question test document. Replace it with your finished paper before going live.</div>}</section></div>}
      {tab === 'questions' && <div className="admin-question-grid"><section className="admin-panel"><div className="panel-top"><span>{editingId ? 'EDIT QUESTION' : 'NEW QUESTION'}</span><span>01</span></div><h2>{editingId ? 'Refine this question.' : 'Add a question.'}</h2><p>Each question has four options, one correct answer and a clear explanation shown after the test.</p><form onSubmit={saveQuestion} className="admin-form"><label htmlFor="question-subject">Subject</label><select id="question-subject" value={question.subjectId} onChange={e => setQuestion({ ...question, subjectId:e.target.value })}>{catalog.subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><label htmlFor="question-prompt">Question</label><textarea id="question-prompt" required minLength={15} value={question.prompt} onChange={e => setQuestion({ ...question, prompt:e.target.value })} placeholder="Write the full question…"/>{question.options.map((opt,i) => <React.Fragment key={i}><label htmlFor={`option-${i}`}>Option {String.fromCharCode(65+i)}</label><input id={`option-${i}`} required value={opt} onChange={e => setQuestion({ ...question, options:question.options.map((o,n) => n===i ? e.target.value : o) })}/></React.Fragment>)}<label htmlFor="correct-option">Correct answer</label><select id="correct-option" value={question.correctIndex} onChange={e => setQuestion({ ...question, correctIndex:Number(e.target.value) })}>{['A','B','C','D'].map((l,i) => <option key={l} value={i}>Option {l}</option>)}</select><label htmlFor="question-explanation">Explanation</label><textarea id="question-explanation" required minLength={10} value={question.explanation} onChange={e => setQuestion({ ...question, explanation:e.target.value })} placeholder="Explain why the answer is correct…"/><div className="admin-form-actions"><button className="btn btn-dark" disabled={busy} type="submit">{editingId ? <Save size={17}/> : <Plus size={17}/>} {editingId ? 'Save question' : 'Add question'}</button>{editingId && <button type="button" className="panel-link" onClick={() => { setEditingId(null); setQuestion(emptyQuestion); }}>Cancel edit</button>}</div></form></section><section className="admin-panel"><div className="panel-top"><span>QUESTION BANK</span><span>{overview.questions.length} LIVE</span></div><h2>Published questions.</h2><div className="admin-question-list">{overview.questions.map((q,i) => <article key={q.id}><span>{String(i+1).padStart(2,'0')} / {catalog.subjects.find(s => s.id===q.subjectId)?.short || q.subjectId}</span><h3>{q.prompt}</h3><div><button onClick={() => edit(q)}>Edit</button><button onClick={() => remove(q)}><Trash2 size={16}/> Delete</button></div></article>)}</div></section></div>}
      {tab === 'orders' && <section className="admin-panel"><div className="panel-top"><span>VERIFIED ACCESS</span><span>{overview.orders.length} ORDERS</span></div><h2>Student purchases.</h2><p>Real purchases and local test orders are labeled separately.</p><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Date</th><th>Email</th><th>Mobile</th><th>Amount</th><th>Type</th></tr></thead><tbody>{overview.orders.map(o => <tr key={o.id}><td>{new Date(o.paidAt).toLocaleDateString()}</td><td>{o.email}</td><td>+91 {o.phone}</td><td>₹{o.amount}</td><td><span className={o.mode==='live'?'order-live':'order-test'}>{o.mode==='live'?'Paid':'Test'}</span></td></tr>)}</tbody></table>{!overview.orders.length && <div className="orders-empty">No purchases yet. Verified orders will appear here.</div>}</div></section>}
    </>}
  </div></main>;
}
